"""add is delete for like

Revision ID: 495de9d97683
Revises: 5594c9260088
Create Date: 2019-05-26 15:30:55.557296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495de9d97683'
down_revision = '5594c9260088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'is_delete')
    # ### end Alembic commands ###
