"""add email for users

Revision ID: 0ae9ad75885e
Revises: 0c2e5a32676d
Create Date: 2019-05-24 09:09:28.950798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae9ad75885e'
down_revision = '0c2e5a32676d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uses', sa.Column('email', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uses', 'email')
    # ### end Alembic commands ###
