"""change_users

Revision ID: 73347f318210
Revises: 5664537597f5
Create Date: 2019-05-31 19:49:11.621201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73347f318210'
down_revision = '5664537597f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
