"""create posts table

Revision ID: 0308e1b5a6ef
Revises: 17b4401f710b
Create Date: 2019-05-17 21:47:07.466792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0308e1b5a6ef'
down_revision = '17b4401f710b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
