"""add email for users

Revision ID: 17b4401f710b
Revises: 0e6a10ec86c9
Create Date: 2019-05-17 20:51:54.351115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b4401f710b'
down_revision = '0e6a10ec86c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
