"""add_email_for_users

Revision ID: 5816741e3c48
Revises: a2592c33e476
Create Date: 2019-05-30 20:41:57.651288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5816741e3c48'
down_revision = 'a2592c33e476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
